extends:
  - ../../.eslintrc.yaml
ignorePatterns:
  - '!**/*'
overrides:
  - files:
      - '*.ts'
    extends:
      - 'plugin:@nrwl/nx/angular'
      - 'plugin:@angular-eslint/template/process-inline-templates'
    rules:
      '@angular-eslint/directive-selector':
        - error
        - type: attribute
          prefix: pipeline-project-template
          style: camelCase
      '@angular-eslint/component-selector':
        - error
        - type: element
          prefix: pipeline-project-template
          style: kebab-case
  - files:
      - '*.html'
    extends:
      - 'plugin:@nrwl/nx/angular-template'
    rules: {}
