name: Branch

on: [push, pull_request]

env:
  DATABASE_URL: file:../data/dev.db
  ENV: 3000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - name: Get dependencies
        run: npm ci
      #      - name: Setup Nx SHAs
      #        uses: nrwl/nx-set-shas@v3
      - name: Build
        run: npx nx run-many --target=build --parallel=3

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - name: Get dependencies
        run: npm ci
      #      - name: Setup Nx SHAs
      #        uses: nrwl/nx-set-shas@v3
      - name: Test
        run: npx nx run-many --target=test --parallel=3 --ci --code-coverage

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - name: Get dependencies
        run: npm ci
      #      - name: Setup Nx SHAs
      #        uses: nrwl/nx-set-shas@v3
      - name: Lint
        run: npx nx run-many --target=lint --parallel=3

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - name: Get dependencies
        run: npm ci
      #      - name: Setup Nx SHAs
      #        uses: nrwl/nx-set-shas@v3
      - name: Setup Prisma DB
        run: npx prisma migrate deploy
      - name: Seed DB
        run: npx prisma db seed
      - name: Run E2E Tests
        run: npx nx run-many --target=e2e --parallel=3
      - name: Save e2e artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Cypress
          path: dist/cypress

  deploy-frontend:
    runs-on: ubuntu-latest
    environment: Deployment
    if: ${{ github.ref_name == 'main' }}
    needs:
      - build
      - test
      - lint
      - e2e
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_DEPLOYMENT_USERNAME }}
          password: ${{ secrets.DOCKER_DEPLOYMENT_SECRET }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.docker/frontend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_DEPLOYMENT_USERNAME }}/research-data-showcase-frontend:latest
          build-args: |
            BRANCH=${{ env.BRANCH }}

  deploy-backend:
    runs-on: ubuntu-latest
    environment: Deployment
    if: ${{ github.ref_name == 'main' }}
    needs:
      - build
      - test
      - lint
      - e2e
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_DEPLOYMENT_USERNAME }}
          password: ${{ secrets.DOCKER_DEPLOYMENT_SECRET }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.docker/backend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_DEPLOYMENT_USERNAME }}/research-data-showcase-backend:latest
